services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hr
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
