CREATE TABLE IF NOT EXISTS pdf_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_number INTEGER NOT NULL UNIQUE,
    original_file_name VARCHAR(255) NOT NULL,
    content BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS pdf_template_fields (
    template_id BIGINT NOT NULL REFERENCES pdf_templates (id) ON DELETE CASCADE,
    type VARCHAR(32) NOT NULL,
    page_number INTEGER NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    font_size DOUBLE PRECISION NOT NULL,
    font_name VARCHAR(255),
    color VARCHAR(255),
    date_format VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_pdf_template_fields_template_id
    ON pdf_template_fields (template_id);
