ALTER TABLE pdf_template_fields
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'pdf_template_fields'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE pdf_template_fields
            ADD CONSTRAINT pdf_template_fields_pkey PRIMARY KEY (id);
    END IF;
END $$;
