CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_positions_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id BIGINT NOT NULL,
    subject_template TEXT NOT NULL,
    body_template TEXT NOT NULL,
    CONSTRAINT uq_email_templates_position UNIQUE (position_id),
    CONSTRAINT fk_email_templates_position
        FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE CASCADE
);

ALTER TABLE pdf_templates
    ADD COLUMN IF NOT EXISTS position_id BIGINT,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_pdf_templates_position'
    ) THEN
        ALTER TABLE pdf_templates
            ADD CONSTRAINT fk_pdf_templates_position
                FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pdf_templates_position_id
    ON pdf_templates (position_id);

UPDATE pdf_templates
SET name = original_file_name
WHERE name IS NULL;
